### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by benwaffle**

### CODE REVIEW

**Comment by keevindoherty** [comment]
Why?

**Comment by benwaffle** [comment]
on some distros, python3 is the default but you want a python2 environment

**Comment by keevindoherty** [comment]
Your change is specific to Arch, I think. On most distros virtualenv is what you want, but I'll throw in a comment about virtualenv2 on Arch. Thanks dude!

**Comment by benwaffle** [comment]
Does virtualenv2 exist on other distros?

**Comment by keevindoherty** [comment]
Not to my knowledge

**Pull request closed without merging**
